---
http:
  services:
    srv-agents:
      loadBalancer:
        servers:
          - url: "http://10.0.0.10:8700"
        passHostHeader: true

  middlewares:
    agents-auth:
      basicAuth:
        users:
          - "admin:$2b$10$<BCRYPT-HASH>"

  routers:
    rtr-agents:
      rule: "Host(`agents.example.com`)"
      service: srv-agents
      entryPoints:
        - websecure
      middlewares:
        - agents-auth
